Class {
	#name : #PhLNullImage,
	#superclass : #Object,
	#category : #'PharoLauncher-Spec-New'
}

{ #category : #accessing }
PhLNullImage >> arch [
	
	^ ''
]

{ #category : #accessing }
PhLNullImage >> description [
	
	^ '<no description given>'
]

{ #category : #accessing }
PhLNullImage >> lastModification [
	
	^ nil
]

{ #category : #accessing }
PhLNullImage >> location [

	^ nil
]

{ #category : #accessing }
PhLNullImage >> name [
	^ ''
]

{ #category : #accessing }
PhLNullImage >> originTemplateName [
	
	^ ''
]
