"
I stores metadata on true and false positive critics. These meta data are used by the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestPharoLauncherTests,
	#superclass : #Object,
	#category : 'PharoLauncher-Tests-Core'
}

{ #category : #'meta data' }
ManifestPharoLauncherTests class >> rejectClasses [
^ #()
]

{ #category : #'meta data' }
ManifestPharoLauncherTests class >> rejectRules [
^ #()
]
