"
Null pattern for a PhLImage.
Used to display information when no image is selected.
"
Class {
	#name : #PhLNullImage,
	#superclass : #Object,
	#category : #'PharoLauncher-Spec2'
}

{ #category : #accessing }
PhLNullImage >> architecture [
	
	^ ''
]

{ #category : #accessing }
PhLNullImage >> description [
	
	^ '<no description given>'
]

{ #category : #accessing }
PhLNullImage >> lastModification [
	
	^ nil
]

{ #category : #accessing }
PhLNullImage >> location [

	^ nil
]

{ #category : #accessing }
PhLNullImage >> name [
	^ ''
]

{ #category : #accessing }
PhLNullImage >> originTemplateName [
	
	^ ''
]
